### ISSUE TITLE
Dependencies not met for transmission

### ISSUE THREAD

**Issue by shnabz** [OpenELEC/unofficial-addons#155]
I'm running OE 6.0.3

> CAddonInstallJob[service.downloadmanager.transmission]: requires os.libreelec.tv version 0.0.0 which is not available

**Comment by codesnake** [comment]
You are running OpenELEC, but trying to install an addon for LibreELEC.

**Comment by shnabz** [comment]
Why is it in the OpenELEC (unofficial) repository?

**Comment by tcamargo** [comment]
Got a similar message (unable to update due to unmet dependencies). I hadn't checked the logs but I can see an update pending from LSELLENS repo (7.0.2). Do you have that repository in your OE installation? I am running 7.0.1.

**Comment by shnabz** [comment]
I do have lsellens repo yes, could have sworn I downloaded transmission from OE's unofficial repo.
